/**
 * The filesystem and attachment half of the adapter.
 *
 * Core defines the {@link import('../core/types.js').SpoolSink} seam and never
 * touches a filesystem; this module is the implementation, and it degrades
 * instead of failing:
 *
 * | Situation | Behaviour |
 * |---|---|
 * | No filesystem service mounted | Nothing is persisted; oversized results degrade to a skeleton that says so |
 * | No attachment service mounted | Rendered images come back as files and URLs, without an inline image block |
 * | A write fails | The call still succeeds; the summary simply carries no path |
 *
 * Persisting a spill file must never be the reason a question cannot be
 * answered.
 *
 * @module dsh-plugin-figma/adapter/spool-fs
 */

import { mkdir, writeFile } from 'node:fs/promises'
import { dirname } from 'node:path'

import { assertSafeSpoolName } from '../core/spool-sink.js'

/** Media types the durable attachment path accepts. */
const ATTACHABLE = new Set(['image/png', 'image/jpeg', 'image/webp', 'image/gif'])

/**
 * Build the persistence sink for one plugin instance.
 *
 * The filesystem and attachment services are read through getters rather than
 * captured once, so a service mounted after activation is still picked up and a
 * disposed one is not held past its lifetime.
 *
 * @param {object} options - Wiring options.
 * @param {() => any} options.getFs - Returns the filesystem service, or `undefined`.
 * @param {() => any} options.getAttachments - Returns the attachment store, or `undefined`.
 * @param {string} options.spoolDir - Directory for spill files, relative to the session workspace.
 * @param {(message: string) => void} [options.warn] - Called once per failed persistence attempt.
 * @returns {import('../core/types.js').SpoolSink} Sink.
 */
export function createSpoolSink(options) {
  const { getFs, getAttachments, spoolDir } = options
  const warn = options.warn ?? (() => {})

  /**
   * Resolve one spool file to a host filesystem target.
   *
   * @param {string} name - Relative name inside the spool directory.
   * @param {import('../core/types.js').SpoolContext} [context] - Per-call context.
   * @returns {Promise<{fs: any, target: any}|undefined>} Resolved target, or `undefined` when unusable.
   */
  async function resolveTarget(name, context) {
    const fs = getFs()
    if (fs === undefined) return undefined
    // Names are generated by the core, never taken from model input, but the
    // guard is here so that stays true under future callers.
    assertSafeSpoolName(name)
    const target = await fs.resolve(`${spoolDir}/${name}`, { cwd: context?.cwd, signal: context?.signal })
    return { fs, target }
  }

  return {
    async write(name, content, context) {
      try {
        const resolved = await resolveTarget(name, context)
        if (resolved === undefined) return undefined
        await resolved.fs.writeText(resolved.target, content, undefined, context?.signal)
        return String(resolved.target.displayPath)
      } catch (error) {
        warn(`could not save an oversized Figma result: ${describe(error)}`)
        return undefined
      }
    },

    async writeImage(name, bytes, context) {
      try {
        const resolved = await resolveTarget(name, context)
        if (resolved === undefined) return undefined
        // The filesystem service exposes text and byte *reads* but no byte
        // write, so the bytes go through Node's filesystem using the path the
        // service itself resolved and canonicalized. The target is always the
        // spool directory, and the name is traversal-checked above.
        const processPath = resolved.fs.processPath(resolved.target)
        await mkdir(dirname(processPath), { recursive: true })
        await writeFile(processPath, bytes, { signal: context?.signal })
        return String(resolved.target.displayPath)
      } catch (error) {
        warn(`could not save a rendered Figma image: ${describe(error)}`)
        return undefined
      }
    },

    async saveImage(input) {
      const attachments = getAttachments()
      if (attachments === undefined) return undefined
      if (!ATTACHABLE.has(input.mediaType)) return undefined
      try {
        const ref = await attachments.saveImage({
          data: input.bytes,
          mediaType: input.mediaType,
          name: input.name,
        })
        // A plain, host-free copy: core must not hold a reference to a live
        // service object, and the tool layer re-brands it when it builds the
        // image block.
        return {
          attachmentId: String(ref.attachmentId),
          mediaType: ref.mediaType,
          bytes: ref.bytes,
          width: ref.width,
          height: ref.height,
          ...(ref.name === undefined ? {} : { name: String(ref.name) }),
        }
      } catch (error) {
        warn(`could not attach a rendered Figma image: ${describe(error)}`)
        return undefined
      }
    },
  }
}

/**
 * One-line description of a thrown value.
 *
 * @param {unknown} error - Thrown value.
 * @returns {string} Message.
 */
function describe(error) {
  return error instanceof Error ? error.message : String(error)
}
